export const DATA_TYPES = {
	TEXT: "TEXT",
	NUMBER: "NUMBER",
	RADIO: "RADIO",
	CHECKBOX: "CHECKBOX"
};

export const DISPLAY_TYPES = {
	DEFAULT: "DEFAULT",
	LIST: "LIST",
	DROPDOWN: "DROPDOWN"
};

export const SURVEY_STATUS = {
	DRAFT: "DRAFT",
	PUBLISHED: "PUBLISHED",
	PAUSED: "PAUSED",
	FINISHED: "FINISHED",
	ARCHIVED: "ARCHIVED"
};
